version: 0.2

phases:
  install:
    commands:
      - echo Install npm
      - npm install
  pre_build:
    commands:
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws cloudformation package
        --template-file template.yaml
        --s3-bucket ${BUILD_BUCKET}
        --output-template-file packaged.yaml
artifacts:
  type: zip
  files:
    - packaged.yaml