name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - dev
          - prod
      review_changeset:
        description: Review Changeset
        required: true
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor == 'brycepc'
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@thebetterstore'
      - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: chmod +x ./deploy.sh && ./deploy.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: ${{ inputs.environment }}
          REVIEW_CHANGESET: ${{ inputs.review_changeset }}
          DEPLOY_BUCKET: ${{ vars.DEPLOY_BUCKET }}
